---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: unikraft/pkg-deb
    tag: ((tag))

params:
  DIRTY:

inputs:
  - name: kraft
    path: .

outputs:
  - name: dist

run:
  path: bash
  args:
    - -cex
    - |
      PKG_VENDOR=((vendor)) \
      PKG_DISTRIBUTION=((distribution)) \
      DIRTY=$DIRTY \
      DOCKER= \
      make get-version > dist/version

      PKG_VENDOR=((vendor)) \
      PKG_DISTRIBUTION=((distribution)) \
      APP_VERSION=$(cat dist/version) \
      DOCKER= \
      make pkg-deb
