---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: vito/oci-build-task

params:
  DOCKERFILE: package/docker/Dockerfile.pkg-deb
  CONTEXT: .
  BUILD_ARG_HTTP_PROXY: ((http_proxy))
  BUILD_ARG_HTTPS_PROXY: ((https_proxy))
  # BUILD_ARG_PKG_VENDOR: debian
  # BUILD_ARG_PKG_DISTRIBUTION: stretch

inputs:
  - name: kraft
    path: .

outputs:
  - name: image

caches:
  - path: cache

run:
  path: build
