---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ((vendor))
    tag: ((distribution))

run:
  path: bash
  args:
    - -cex
    - |
      export LANG=C.UTF-8;
      export LC_ALL=C.UTF-8;
      export DEBIAN_FRONTEND=noninteractive;
      apt-get update;
      apt-get install -y wget;
      wget -O unikraft-tools.deb http://releases.unikraft.org/linux/((vendor))/pool/((branch))/u/unikraft-tools/((basename))
      dpkg -i ./unikraft-tools.deb || true
      apt-get install -y -f
      basename="((basename))"
      kraft --version
